### ISSUE TITLE
soft view update/dom diff algorithm

### ISSUE THREAD

**Issue by chexov** [st-js/steel#1]
Hi there. Amazing project.
By any chance were you thinking about react like rendered element updates. Sort of virtual dom paradigm?

**Comment by acraciun** [comment]
Hi,
Well the plan is not exactly to do as react - to see changes on the virtual dom, but rather to detect changes on the model. So the idea was to use STJS code generation features to generate code that implements behind the scenes an Observer pattern. The ideas were more borrowed from Knockout.

The theory was that the changes actually occur in your model and not in your view (DOM). So it's there were you can implement different techniques on how to deal with those changes. By detecting changes in your model, Steel will only update the DOM parts affected by those changes. This allows you to have more complex components renderers that will only be executed when the model changed.
